// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ui0-Myb7oXhkluhM5KVi6O-LMbetTbo',
    appId: '1:830407545487:web:a467ba121182b9a79916fa',
    messagingSenderId: '830407545487',
    projectId: 'ai-app-psychologist',
    authDomain: 'ai-app-psychologist.firebaseapp.com',
    storageBucket: 'ai-app-psychologist.firebasestorage.app',
    measurementId: 'G-BFRQME6VZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5UQkCNFYcD_xzC9ugneOVwII1A6we8Q',
    appId: '1:830407545487:android:502c7bb40993874c9916fa',
    messagingSenderId: '830407545487',
    projectId: 'ai-app-psychologist',
    storageBucket: 'ai-app-psychologist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTKKG1aNDAJRN8YdU0WoElbPsggeALjKQ',
    appId: '1:830407545487:ios:afafcb74eebff0f99916fa',
    messagingSenderId: '830407545487',
    projectId: 'ai-app-psychologist',
    storageBucket: 'ai-app-psychologist.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTKKG1aNDAJRN8YdU0WoElbPsggeALjKQ',
    appId: '1:830407545487:ios:afafcb74eebff0f99916fa',
    messagingSenderId: '830407545487',
    projectId: 'ai-app-psychologist',
    storageBucket: 'ai-app-psychologist.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ui0-Myb7oXhkluhM5KVi6O-LMbetTbo',
    appId: '1:830407545487:web:46ca50c1ca14a8fc9916fa',
    messagingSenderId: '830407545487',
    projectId: 'ai-app-psychologist',
    authDomain: 'ai-app-psychologist.firebaseapp.com',
    storageBucket: 'ai-app-psychologist.firebasestorage.app',
    measurementId: 'G-2J4MTZB7EP',
  );
}
